<?php
/**
 * AI Powered page template.
 *
 * Ported from app/ai/page.tsx's five sections, in source order: the ai-hero
 * (two-column, Claude badge + copy, with the AiDemo widget), "The Full Flow"
 * (the AiPipeline widget), "Model Guidance" (a dark section of four model
 * cards), "Approved Stack" (ten chips), and "What We Build" (five offering
 * cards on a dark section).
 *
 * AiDemo and AiPipeline are the Plan 3b interactive widgets, rendered by PHP in
 * a complete finished state and enhanced by assets/js/public-widgets.js
 * (progressive enhancement; both honour prefers-reduced-motion). Everything
 * else is static. This page's `.ai-*` styles are already in public.css.
 *
 * The <main><div> wrapper is required, not stylistic: globals.css targets
 * `main > div > .sec:last-child` to zero the final section's bottom padding.
 *
 * @package BlueWorxSite
 */

// Prevent direct file access.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// Static trusted arrow SVG, sized by `.btn svg` / `.svc-link svg`. Ported
// verbatim from the ARROW constant in app/ai/page.tsx (not a blueworx_icon).
$blueworx_ai_arrow = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="7" y1="17" x2="17" y2="7"/><polyline points="7 7 17 7 17 17"/></svg>';

// AiDemo (Plan 3b): static trusted sparkle icon for the prompt row, ported
// verbatim from components/AiDemo.tsx's `.pi` svg.
$blueworx_ai_demo_sparkle = '<svg viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3l1.9 5.1L19 10l-5.1 1.9L12 17l-1.9-5.1L5 10z"/></svg>';

// AiDemo (Plan 3b): the 11 syntax-highlighted code lines, ported verbatim
// (inner markup only) from components/AiDemo.tsx's CODE_LINES array.
$blueworx_ai_demo_code_lines = array(
	'<span class="c">// booking.tsx — generated by BlueWorx AI</span>',
	'<span><span class="k">import</span> <span class="t">{ Theme, Card, Button }</span> <span class="k">from</span> <span class="s">&#039;@radix-ui/themes&#039;</span></span>',
	'<span><span class="k">import</span> <span class="t">{ Calendar }</span> <span class="k">from</span> <span class="s">&#039;lucide-react&#039;</span></span>',
	'<span>&nbsp;</span>',
	'<span><span class="k">export function</span> <span class="f">BookingForm</span>() {</span>',
	'<span>  <span class="k">return</span> (</span>',
	'<span>    <span class="t">&lt;Theme</span> <span class="f">accentColor</span>=<span class="s">&quot;indigo&quot;</span><span class="t">&gt;</span></span>',
	'<span>      <span class="t">&lt;Card&gt;&lt;Calendar /&gt; &lt;Button&gt;</span>Book now<span class="t">&lt;/Button&gt;&lt;/Card&gt;</span></span>',
	'<span>    <span class="t">&lt;/Theme&gt;</span></span>',
	'<span>  )</span>',
	'<span>}</span>',
);

$blueworx_ai_models = array(
	array(
		'icon'  => 'gauge',
		'tier'  => 'Haiku',
		'title' => __( 'Fast & light', 'bluegroup-project-blueworx' ),
		'role'  => __( 'For quick, mechanical, high-volume work and simple tweaks.', 'bluegroup-project-blueworx' ),
		'items' => array( __( 'High-volume edits', 'bluegroup-project-blueworx' ), __( 'Simple design tweaks', 'bluegroup-project-blueworx' ), __( 'Routine changes', 'bluegroup-project-blueworx' ) ),
	),
	array(
		'icon'  => 'code',
		'tier'  => 'Sonnet',
		'title' => __( 'The default', 'bluegroup-project-blueworx' ),
		'role'  => __( 'Our everyday workhorse for building, planning and most design.', 'bluegroup-project-blueworx' ),
		'items' => array( __( 'Day-to-day coding', 'bluegroup-project-blueworx' ), __( 'Issues & milestones', 'bluegroup-project-blueworx' ), __( 'Everyday screens', 'bluegroup-project-blueworx' ) ),
	),
	array(
		'icon'  => 'sparkles',
		'tier'  => 'Opus',
		'title' => __( 'Deep reasoning', 'bluegroup-project-blueworx' ),
		'role'  => __( 'For new or unclear briefs, hard bugs and demanding design.', 'bluegroup-project-blueworx' ),
		'items' => array( __( 'New project briefs', 'bluegroup-project-blueworx' ), __( 'Hard bugs & architecture', 'bluegroup-project-blueworx' ), __( 'Demanding design', 'bluegroup-project-blueworx' ) ),
	),
	array(
		'icon'  => 'zap',
		'tier'  => 'Fable',
		'title' => __( 'The big jobs', 'bluegroup-project-blueworx' ),
		'role'  => __( 'Reserved for the largest builds and toughest design challenges.', 'bluegroup-project-blueworx' ),
		'items' => array( __( 'Major migrations', 'bluegroup-project-blueworx' ), __( 'Multi-day builds', 'bluegroup-project-blueworx' ), __( 'Toughest design', 'bluegroup-project-blueworx' ) ),
	),
);

$blueworx_ai_stack = array(
	array(
		'name' => 'Radix Themes',
		'sub'  => __( 'components', 'bluegroup-project-blueworx' ),
	),
	array(
		'name' => 'lucide-react',
		'sub'  => __( 'icons', 'bluegroup-project-blueworx' ),
	),
	array(
		'name' => 'Tailwind CSS',
		'sub'  => __( 'styling', 'bluegroup-project-blueworx' ),
	),
	array(
		'name' => 'GSAP',
		'sub'  => __( 'motion', 'bluegroup-project-blueworx' ),
	),
	array(
		'name' => 'Refero',
		'sub'  => __( 'tokens', 'bluegroup-project-blueworx' ),
	),
	array(
		'name' => 'Playwright',
		'sub'  => __( 'testing', 'bluegroup-project-blueworx' ),
	),
	array(
		'name' => 'GitHub',
		'sub'  => __( 'source', 'bluegroup-project-blueworx' ),
	),
	array(
		'name' => 'Netlify',
		'sub'  => __( 'deploy', 'bluegroup-project-blueworx' ),
	),
	array(
		'name' => 'WordPress',
		'sub'  => __( 'backend', 'bluegroup-project-blueworx' ),
	),
	array(
		'name' => 'Claude Code',
		'sub'  => __( 'build', 'bluegroup-project-blueworx' ),
	),
);

$blueworx_ai_offerings = array(
	array(
		'icon'  => 'doc',
		'title' => __( 'AI-Built Websites', 'bluegroup-project-blueworx' ),
		'desc'  => __( 'Conversion-focused sites generated from your brief and refined by hand. Fast, on-brand and production-ready.', 'bluegroup-project-blueworx' ),
	),
	array(
		'icon'  => 'plug',
		'title' => __( 'AI Plugins & Integrations', 'bluegroup-project-blueworx' ),
		'desc'  => __( 'Custom WordPress plugins and app integrations, built code-first so every change is reviewable through a pull request.', 'bluegroup-project-blueworx' ),
	),
	array(
		'icon'  => 'workflow',
		'title' => __( 'AI Automations & Workflows', 'bluegroup-project-blueworx' ),
		'desc'  => __( 'Connect the tools you already use and let AI-designed workflows handle the busywork end to end.', 'bluegroup-project-blueworx' ),
	),
	array(
		'icon'  => 'server',
		'title' => __( 'Custom AI Tooling', 'bluegroup-project-blueworx' ),
		'desc'  => __( 'Bespoke internal tools and AI features tailored to how your business actually runs day to day.', 'bluegroup-project-blueworx' ),
	),
	array(
		'icon'  => 'palette',
		'title' => __( 'AI-Assisted Design', 'bluegroup-project-blueworx' ),
		'desc'  => __( 'Screens designed in Claude Design on your own design system (Radix, lucide and tokens), ready for a clean handoff.', 'bluegroup-project-blueworx' ),
	),
);

blueworx_public_document_open( array( 'body_class' => 'bw-ai' ) );
blueworx_public_part( 'parts/nav.php' );
?>
<main>
	<div>
		<section class="tech-hero ai-hero">
			<div class="tech-inner">
				<div class="tech-2col">
					<div class="tc-copy">
						<div class="claude-badge">
							<span class="cb-spark"><svg viewBox="0 0 24 24" fill="currentColor"><path d="M12 1.5c.62 5.4 3.6 8.38 9 9-5.4.62-8.38 3.6-9 9-.62-5.4-3.6-8.38-9-9 5.4-.62 8.38-3.6 9-9z"/></svg></span>
							<span class="cb-lbl"><?php esc_html_e( 'Powered by', 'bluegroup-project-blueworx' ); ?></span>
							<b>Claude</b>
							<span class="cb-div"></span>
							<span class="cb-by">Anthropic</span>
						</div>
						<h1 class="h1" style="margin-top:22px"><?php esc_html_e( 'From Prompt to Production — ', 'bluegroup-project-blueworx' ); ?><span class="tech-grad"><?php esc_html_e( 'Built by AI', 'bluegroup-project-blueworx' ); ?></span><?php esc_html_e( ', Shipped by Experts', 'bluegroup-project-blueworx' ); ?></h1>
						<p class="lead" style="margin-top:22px"><?php esc_html_e( 'We build websites, plugins, automations and custom tools with an AI-first process. Claude models turn your brief into production-ready code on a vetted stack, reviewed, tested and shipped by our team.', 'bluegroup-project-blueworx' ); ?></p>
						<div class="hh-cta" style="margin-top:34px">
							<a href="<?php echo esc_url( home_url( '/pricing' ) ); ?>" class="btn btn-white btn-lg"><?php esc_html_e( 'Get a Quote', 'bluegroup-project-blueworx' ); ?></a>
							<a href="<?php echo esc_url( home_url( '/work' ) ); ?>" class="btn btn-outline-w btn-lg">
								<?php
								// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- static trusted arrow markup.
								echo $blueworx_ai_arrow;
								?>
								<?php esc_html_e( 'View Our Work', 'bluegroup-project-blueworx' ); ?>
							</a>
						</div>
						<div class="ai-lead-tags">
							<span><?php esc_html_e( 'Opus · Sonnet · Haiku', 'bluegroup-project-blueworx' ); ?></span><span><?php esc_html_e( 'Radix + Tailwind', 'bluegroup-project-blueworx' ); ?></span><span><?php esc_html_e( 'GSAP motion', 'bluegroup-project-blueworx' ); ?></span>
						</div>
					</div>
					<div class="glass-wrap">
						<div class="ai-demo-root ai-demo-a" data-widget="ai-demo">
							<div class="ai-stages">
								<div class="ai-stage on"><b>1</b><?php esc_html_e( 'Prompt', 'bluegroup-project-blueworx' ); ?><span class="bar"></span></div>
								<div class="ai-stage on"><b>2</b><?php esc_html_e( 'Code', 'bluegroup-project-blueworx' ); ?><span class="bar"></span></div>
								<div class="ai-stage on"><b>3</b><?php esc_html_e( 'Site', 'bluegroup-project-blueworx' ); ?></div>
							</div>
							<div class="ai-demo">
								<div class="ai-demo-head"><i></i><i></i><i></i><span class="lbl"><?php esc_html_e( 'generating', 'bluegroup-project-blueworx' ); ?></span></div>
								<div class="ai-demo-body">
									<div class="ai-prompt">
										<div class="pi">
											<?php
											// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- static trusted markup.
											echo $blueworx_ai_demo_sparkle;
											?>
										</div>
										<div class="pt">
											<span class="ai-typed"><?php echo esc_html__( 'Build a booking website with Stripe checkout + admin dashboard', 'bluegroup-project-blueworx' ); ?></span>
											<span class="ai-caret" style="display:none"></span>
										</div>
									</div>
									<div class="ai-code" style="margin-top:16px">
										<?php
										foreach ( $blueworx_ai_demo_code_lines as $blueworx_ai_demo_line ) :
											// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- static trusted syntax-highlight markup.
											echo '<div class="cl in">' . $blueworx_ai_demo_line . '</div>';
										endforeach;
										?>
									</div>
									<div class="ai-site in" style="margin-top:16px">
										<div class="ai-site-bar">
											<i style="background:#FF5F57"></i>
											<i style="background:#FEBC2E"></i>
											<i style="background:#28C840"></i>
											<span class="u"><?php esc_html_e( 'yourbrand.com/book', 'bluegroup-project-blueworx' ); ?></span>
										</div>
										<div class="ai-site-view">
											<div class="ai-sv-hero"></div>
											<div class="ai-sv-row"><div></div><div></div><div></div></div>
											<div class="ai-sv-line"></div>
											<div class="ai-sv-line w2"></div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>

		<section class="sec">
			<div class="center-head" style="margin-bottom:40px">
				<div class="eyebrow" style="margin-bottom:20px"><?php esc_html_e( 'The Full Flow', 'bluegroup-project-blueworx' ); ?></div>
				<h2 class="h2"><?php esc_html_e( 'From Brief to Deploy, One Continuous Flow', 'bluegroup-project-blueworx' ); ?></h2>
				<p class="lead"><?php esc_html_e( 'A repeatable pipeline where the right Claude model handles each stage, and every change ships through review, tests and version control.', 'bluegroup-project-blueworx' ); ?></p>
			</div>
			<?php
			$blueworx_ai_pipe_steps = array(
				array(
					'n'     => '01',
					'icon'  => 'doc',
					'title' => __( 'Brief', 'bluegroup-project-blueworx' ),
					'desc'  => __( 'Your goal becomes a scoped brief with in-scope, out-of-scope and acceptance criteria.', 'bluegroup-project-blueworx' ),
					'model' => __( 'Claude Opus', 'bluegroup-project-blueworx' ),
				),
				array(
					'n'     => '02',
					'icon'  => 'workflow',
					'title' => __( 'Plan', 'bluegroup-project-blueworx' ),
					'desc'  => __( 'The brief becomes GitHub Milestones and scoped Issues, one per screen or feature.', 'bluegroup-project-blueworx' ),
					'model' => __( 'Claude Sonnet', 'bluegroup-project-blueworx' ),
				),
				array(
					'n'     => '03',
					'icon'  => 'palette',
					'title' => __( 'Design', 'bluegroup-project-blueworx' ),
					'desc'  => __( 'Screens designed on your design system, then handed off to build.', 'bluegroup-project-blueworx' ),
					'model' => __( 'Claude Opus', 'bluegroup-project-blueworx' ),
				),
				array(
					'n'     => '04',
					'icon'  => 'code',
					'title' => __( 'Build', 'bluegroup-project-blueworx' ),
					'desc'  => __( 'Each Issue built on its own branch, following our recipe book and standards.', 'bluegroup-project-blueworx' ),
					'model' => __( 'Claude Sonnet', 'bluegroup-project-blueworx' ),
				),
				array(
					'n'     => '05',
					'icon'  => 'shield',
					'title' => __( 'Review', 'bluegroup-project-blueworx' ),
					'desc'  => __( 'Automated checks, Playwright tests and code review gate every pull request.', 'bluegroup-project-blueworx' ),
					'model' => __( 'Claude Sonnet', 'bluegroup-project-blueworx' ),
				),
				array(
					'n'     => '06',
					'icon'  => 'zap',
					'title' => __( 'Deploy', 'bluegroup-project-blueworx' ),
					'desc'  => __( 'Merged and shipped to Netlify, WordPress or standalone, versioned and logged.', 'bluegroup-project-blueworx' ),
					'model' => __( 'Automated', 'bluegroup-project-blueworx' ),
				),
			);
			?>
			<div class="ai-pipe-shell" data-widget="ai-pipeline">
				<div class="ai-pipe-glow"></div>
				<div class="ai-pipe-status">
					<span><span class="dotp"></span><?php esc_html_e( 'Live Pipeline', 'bluegroup-project-blueworx' ); ?></span>
					<span><?php esc_html_e( 'Brief → Deploy', 'bluegroup-project-blueworx' ); ?></span>
				</div>
				<div class="ai-pipe">
					<?php foreach ( $blueworx_ai_pipe_steps as $blueworx_ai_pipe_i => $blueworx_ai_pipe_step ) : ?>
						<div class="<?php echo 0 === $blueworx_ai_pipe_i ? 'ai-pipe-step on' : 'ai-pipe-step'; ?>">
							<span class="pn"><?php echo esc_html( $blueworx_ai_pipe_step['n'] ); ?></span>
							<div class="pic"><?php blueworx_icon( $blueworx_ai_pipe_step['icon'] ); ?></div>
							<h4><?php echo esc_html( $blueworx_ai_pipe_step['title'] ); ?></h4>
							<p><?php echo esc_html( $blueworx_ai_pipe_step['desc'] ); ?></p>
							<span class="model"><?php echo esc_html( $blueworx_ai_pipe_step['model'] ); ?></span>
						</div>
					<?php endforeach; ?>
				</div>
			</div>
		</section>

		<section class="features-dark">
			<div class="blob" style="width:360px;height:360px;bottom:-140px;right:-120px;opacity:.13"></div>
			<div class="center-head" style="margin-bottom:40px">
				<div class="eyebrow" style="margin-bottom:20px;background:rgba(139,142,255,.09);border-color:rgba(139,142,255,.28);color:#B7B9FF"><?php esc_html_e( 'Model Guidance', 'bluegroup-project-blueworx' ); ?></div>
				<h2 class="h2" style="color:#fff"><?php esc_html_e( 'The Right Claude Model for Every Task', 'bluegroup-project-blueworx' ); ?></h2>
				<p class="fd-sub" style="margin:16px auto 0;max-width:600px;text-align:center"><?php esc_html_e( 'We match each job to the model that fits it best, so you get the right balance of speed, cost and depth on every piece of work.', 'bluegroup-project-blueworx' ); ?></p>
			</div>
			<div class="ai-models">
				<?php foreach ( $blueworx_ai_models as $blueworx_ai_model ) : ?>
					<div class="ai-model">
						<div class="tier"><span class="glyph"><?php blueworx_icon( $blueworx_ai_model['icon'] ); ?></span><?php echo esc_html( $blueworx_ai_model['tier'] ); ?></div>
						<h4><?php echo esc_html( $blueworx_ai_model['title'] ); ?></h4>
						<p class="role"><?php echo esc_html( $blueworx_ai_model['role'] ); ?></p>
						<ul>
							<?php foreach ( $blueworx_ai_model['items'] as $blueworx_ai_item ) : ?>
								<li><?php echo esc_html( $blueworx_ai_item ); ?></li>
							<?php endforeach; ?>
						</ul>
					</div>
				<?php endforeach; ?>
			</div>
		</section>

		<section class="sec">
			<div class="center-head" style="margin-bottom:40px">
				<div class="eyebrow" style="margin-bottom:20px"><?php esc_html_e( 'Approved Stack', 'bluegroup-project-blueworx' ); ?></div>
				<h2 class="h2"><?php esc_html_e( 'Built on Tools We Trust', 'bluegroup-project-blueworx' ); ?></h2>
				<p class="lead"><?php esc_html_e( 'No guesswork. A vetted, approved toolset used consistently across every project.', 'bluegroup-project-blueworx' ); ?></p>
			</div>
			<div class="ai-stack">
				<?php foreach ( $blueworx_ai_stack as $blueworx_ai_chip ) : ?>
					<div class="ai-chip"><?php echo esc_html( $blueworx_ai_chip['name'] ); ?> <small><?php echo esc_html( $blueworx_ai_chip['sub'] ); ?></small></div>
				<?php endforeach; ?>
			</div>
		</section>

		<section class="features-dark">
			<div class="blob" style="width:340px;height:340px;top:-120px;left:-120px;opacity:.14"></div>
			<div class="blob" style="width:300px;height:300px;bottom:-120px;right:-100px;opacity:.11"></div>
			<div class="center-head" style="margin-bottom:52px">
				<div class="eyebrow" style="margin-bottom:20px;background:rgba(139,142,255,.09);border-color:rgba(139,142,255,.28);color:#B7B9FF"><?php esc_html_e( 'What We Build', 'bluegroup-project-blueworx' ); ?></div>
				<h2 class="h2" style="color:#fff"><?php esc_html_e( 'AI Offerings, Built for Real Businesses', 'bluegroup-project-blueworx' ); ?></h2>
				<p class="fd-sub" style="margin:16px auto 0;max-width:620px;text-align:center"><?php esc_html_e( 'Every build runs through our AI-first process: production-ready code on a vetted stack, reviewed and shipped by our team.', 'bluegroup-project-blueworx' ); ?></p>
			</div>
			<div class="ai-off-grid">
				<?php foreach ( $blueworx_ai_offerings as $blueworx_ai_offering ) : ?>
					<div class="fc">
						<div class="fi"><?php blueworx_icon( $blueworx_ai_offering['icon'] ); ?></div>
						<h3><?php echo esc_html( $blueworx_ai_offering['title'] ); ?></h3>
						<p><?php echo esc_html( $blueworx_ai_offering['desc'] ); ?></p>
						<span class="svc-link">
							<?php esc_html_e( 'Learn more', 'bluegroup-project-blueworx' ); ?>
							<?php
							// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- static trusted arrow markup.
							echo $blueworx_ai_arrow;
							?>
						</span>
					</div>
				<?php endforeach; ?>
			</div>
		</section>
	</div>
</main>
<?php
blueworx_public_part( 'parts/footer.php' );
blueworx_public_document_close();
