"use client";

import { useEffect, useRef, useState } from "react";

const MSG = "Build a booking website with Stripe checkout + admin dashboard";

const CODE_LINES: React.ReactNode[] = [
  <span key="1" className="c">{"// booking.tsx — generated by BlueWorx AI"}</span>,
  <span key="2"><span className="k">import</span> <span className="t">{"{ Theme, Card, Button }"}</span> <span className="k">from</span> <span className="s">&apos;@radix-ui/themes&apos;</span></span>,
  <span key="3"><span className="k">import</span> <span className="t">{"{ Calendar }"}</span> <span className="k">from</span> <span className="s">&apos;lucide-react&apos;</span></span>,
  <span key="4">&nbsp;</span>,
  <span key="5"><span className="k">export function</span> <span className="f">BookingForm</span>() {"{"}</span>,
  <span key="6">{"  "}<span className="k">return</span> (</span>,
  <span key="7">{"    "}<span className="t">&lt;Theme</span> <span className="f">accentColor</span>=<span className="s">&quot;indigo&quot;</span><span className="t">&gt;</span></span>,
  <span key="8">{"      "}<span className="t">&lt;Card&gt;&lt;Calendar /&gt; &lt;Button&gt;</span>Book now<span className="t">&lt;/Button&gt;&lt;/Card&gt;</span></span>,
  <span key="9">{"    "}<span className="t">&lt;/Theme&gt;</span></span>,
  <span key="10">{"  "})</span>,
  <span key="11">{"}"}</span>,
];

// Hero prompt → code → site loop, ported from the design export's initAiDemo.
export default function AiDemo() {
  const [typed, setTyped] = useState("");
  const [stage, setStage] = useState(0);
  const [codeShown, setCodeShown] = useState(0);
  const [siteIn, setSiteIn] = useState(false);
  const [caretVisible, setCaretVisible] = useState(true);
  const alive = useRef(true);

  useEffect(() => {
    alive.current = true;
    const wait = (ms: number) => new Promise((res) => setTimeout(res, ms));
    const loop = async () => {
      while (alive.current) {
        setStage(0);
        setTyped("");
        setCodeShown(0);
        setSiteIn(false);
        setCaretVisible(true);
        await wait(450);
        if (!alive.current) return;
        for (let i = 1; i <= MSG.length; i++) {
          if (!alive.current) return;
          setTyped(MSG.slice(0, i));
          await wait(26);
        }
        await wait(600);
        if (!alive.current) return;
        setCaretVisible(false);
        setStage(1);
        for (let i = 1; i <= CODE_LINES.length; i++) {
          if (!alive.current) return;
          setCodeShown(i);
          await wait(140);
        }
        await wait(550);
        if (!alive.current) return;
        setStage(2);
        setSiteIn(true);
        await wait(3400);
      }
    };
    loop();
    return () => {
      alive.current = false;
    };
  }, []);

  return (
    <div className="ai-demo-root ai-demo-a">
      <div className="ai-stages">
        <div className={stage >= 0 ? "ai-stage on" : "ai-stage"}><b>1</b>Prompt<span className="bar"></span></div>
        <div className={stage >= 1 ? "ai-stage on" : "ai-stage"}><b>2</b>Code<span className="bar"></span></div>
        <div className={stage >= 2 ? "ai-stage on" : "ai-stage"}><b>3</b>Site</div>
      </div>
      <div className="ai-demo">
        <div className="ai-demo-head"><i></i><i></i><i></i><span className="lbl">generating</span></div>
        <div className="ai-demo-body">
          <div className="ai-prompt">
            <div className="pi">
              <svg viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M12 3l1.9 5.1L19 10l-5.1 1.9L12 17l-1.9-5.1L5 10z" />
              </svg>
            </div>
            <div className="pt">
              <span className="ai-typed">{typed}</span>
              <span className="ai-caret" style={caretVisible ? undefined : { display: "none" }}></span>
            </div>
          </div>
          <div className="ai-code" style={{ marginTop: 16 }}>
            {CODE_LINES.map((line, i) => (
              <div key={i} className={i < codeShown ? "cl in" : "cl"}>{line}</div>
            ))}
          </div>
          <div className={siteIn ? "ai-site in" : "ai-site"} style={{ marginTop: 16 }}>
            <div className="ai-site-bar">
              <i style={{ background: "#FF5F57" }}></i>
              <i style={{ background: "#FEBC2E" }}></i>
              <i style={{ background: "#28C840" }}></i>
              <span className="u">yourbrand.com/book</span>
            </div>
            <div className="ai-site-view">
              <div className="ai-sv-hero"></div>
              <div className="ai-sv-row"><div></div><div></div><div></div></div>
              <div className="ai-sv-line"></div>
              <div className="ai-sv-line w2"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
